name: Release Docker

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare lowercase Docker username
        id: prep
        run: |
          echo "DOCKER_USER=$(echo \"${DOCKERHUB_USERNAME}\" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Show ref info
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "DOCKER_USER(lower)=${{ env.DOCKER_USER }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_USER }}/morpho-analytics:latest
            ${{ env.DOCKER_USER }}/morpho-analytics:${{ github.ref_name }}
